apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "authash.fullname" . }}
  labels:
    app: {{ template "authash.name" . }}
    chart: {{ template "authash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "authash.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "authash.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AUTHHASH_RECAPTCHA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: authhash
                  key: AUTHHASH_RECAPTCHA_PRIVATE_KEY
            - name: AUTHHASH_APIKEY
              valueFrom:
                secretKeyRef:
                  name: authhash
                  key: AUTHHASH_APIKEY
            - name: AUTHHASH_PORT
              value: "80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
